# Tugas Presentasi 1

## Anggota

1.Farhan Setya Dhitama     165150201111285<br>
2.Ludgerus Darell Perwara 165150207111073<br>
3.Titus Christian         165150200111100<br>
4.Mahendra Okza Pradhana  165150200111079<br>

## Topik Presentasi : Numpy

Pemrograman Python dan NumPy

## Isi Materi

NUMPY <br>

<ol>
    <li>Create Array</li>
    <li>Combining Array</li>
    <li>Operation</li>
    <li>Logical Operation</li>
    <li>Indexing and Slicing</li>
    <li>Iterating over Array</li>
    <li>Statistic Function</li>
</ol>

## ----------------

In [1]:
height=[1.45,1.68,1.22,1.91,1.81]
height

[1.45, 1.68, 1.22, 1.91, 1.81]

In [2]:
weight=[65,60,45,55,30]
weight

[65, 60, 45, 55, 30]

In [3]:
#BMI = height*weight**2 
#will raise an error 

print(weight*2)

try:
    BMI = height*weight**2
except Exception as e:
    print('Error raised!', str(e))

#Lets try to Use List Comprehension but see the code complexity to read
height_list = [ (item**2) for item in height ]
bmi_list = [ weight[index] / value for index, value in enumerate(height_list) ]
print(bmi_list)

[65, 60, 45, 55, 30, 65, 60, 45, 55, 30]
Error raised! unsupported operand type(s) for ** or pow(): 'list' and 'int'
[30.915576694411413, 21.258503401360546, 30.233808116097823, 15.076341109070475, 9.157229632795092]


In [1]:
import numpy as np

In [5]:
np_height=np.array(height)
np_weight=np.array(weight)


In [6]:
BMI = np_weight/np_height**2
print(BMI)

[ 30.91557669  21.2585034   30.23380812  15.07634111   9.15722963]


## 1.Create Array

In [7]:
listA = [1, 2, 3]
arrayFromList = np.array(listA)

arrayA=np.array([3,4,5])   #Create Array 1 Dimension

print(arrayFromList)

print(type(arrayA))        #Print type numpy.ndArray

print(arrayA.shape)        # Prints "(3,)"

print(arrayA[0], arrayA[1], arrayA[2])   # Prints "3 4 5"

arrayA[0] = 6              # Change an element of the array

print(arrayA)              # Prints "[6, 4, 5]"

[1 2 3]
<class 'numpy.ndarray'>
(3,)
3 4 5
[6 4 5]


In [8]:
a = np.zeros((2,2))  # Create an array of all zeros
print('zeros', a,'\n')             

b = np.ones((1,2))   # Create an array of all ones
print('ones', b,'\n')              

c = np.linspace(0, 4, 9) #create array from 0 into 4 which partitioned into 9 parts/index
print('linspace', c)
print('linspace shape', c.shape, '\n')

d = np.eye(2)        # Create a 2x2 identity matrix
print('eye', d, '\n')              
    
e = np.random.random((2,2)) # Create an array filled with random values
print('random', e)                    

zeros [[ 0.  0.]
 [ 0.  0.]] 

ones [[ 1.  1.]] 

linspace [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4. ]
linspace shape (9,) 

eye [[ 1.  0.]
 [ 0.  1.]] 

random [[ 0.90200975  0.03276549]
 [ 0.65007173  0.10686295]]


In [9]:
np.arange(3)   


#np.arange(3.0)


#np.arange(3,7)


#np.arange(3,7,2)


array([0, 1, 2])

## 2.Combining Array

In [2]:
array1=np.array([[3,4],[5,6]])
array2=np.array([[7,8]])
np.concatenate((array1,array2),axis=0)  #Combining Array

array([[3, 4],
       [5, 6],
       [7, 8]])

In [3]:
np.concatenate((array1,array2.T),axis=1)

array([[3, 4, 7],
       [5, 6, 8]])

In [4]:
np.concatenate((array1,array2),axis=None)

array([3, 4, 5, 6, 7, 8])

## 3.Operations

In [13]:
array1=np.array([[3,4,5],[6,7,8],[9,10,11]])
print(array1)
array1.shape

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


(3, 3)

In [14]:
array2=np.array([[1,2,3]])
print(array2)
array2.shape

[[1 2 3]]


(1, 3)

In [15]:
np.add(array1,array2)

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [16]:
np.subtract(array1,array2)

array([[2, 2, 2],
       [5, 5, 5],
       [8, 8, 8]])

In [17]:
np.multiply(array1,array2)

array([[ 3,  8, 15],
       [ 6, 14, 24],
       [ 9, 20, 33]])

In [18]:
np.divide(array1,array2)

array([[ 3.        ,  2.        ,  1.66666667],
       [ 6.        ,  3.5       ,  2.66666667],
       [ 9.        ,  5.        ,  3.66666667]])

In [19]:
a = np.array([10,100,1000]) 

print(a) 

print('Applying power function:')
print(np.power(a,2))
print('\n')  

[  10  100 1000]
Applying power function:
[    100   10000 1000000]




## 4.Logical Operator on Array

In [20]:
array1=np.array([True, False, True, False, True, False])
print(array1)
array1.shape

[ True False  True False  True False]


(6,)

In [21]:
array2=np.array([True, False, False, True, True, True])
print(array2)
array2.shape

[ True False False  True  True  True]


(6,)

In [22]:
array3=np.array([1, 3, 5, 2, 7, 10])
print(array3)
array3.shape

[ 1  3  5  2  7 10]


(6,)

In [23]:
np.where(array3 % 2 == 0, 1, 0)

array([0, 0, 0, 1, 0, 1])

In [24]:
np.logical_and(array1, array2)

array([ True, False, False, False,  True, False], dtype=bool)

In [25]:
np.logical_or(array1, array2)

array([ True, False,  True,  True,  True,  True], dtype=bool)

In [26]:
np.logical_not(array1)

array([False,  True, False,  True, False,  True], dtype=bool)

In [27]:
np.logical_xor(array1, array2)

array([False, False,  True,  True, False,  True], dtype=bool)

## 5.Indexing & Slicing

In [28]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
a[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
step = 3 #step is like how many increment will used when slicing numpy array
print('Step' , step, a[-6:10:step])

step = 2
print('Step', step, a[-6:10:step])

Step 3 [ 7 10]
Step 2 [7 9]


![title](indexArray.png)

## Iterating Over Array

In [31]:
import numpy as np
#reshape takes 2 argument, the 1st one is row and the 2nd one is column
a = np.arange(6).reshape(2,3) 
a

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [34]:
#From docs: 
#class numpy.nditer[source]
#Efficient multi-dimensional iterator object to iterate over arrays.

for x in np.nditer(a):
    print(x, end=' ')

0 1 2 3 4 5 

In [35]:
#If not using nditer

for idx, value in enumerate(a):
    print('Index', idx, value)
    for y in x:
        print(y, end=' ')
    print('\n')

Index 0 [0 1]


TypeError: iteration over a 0-d array

## Statistic Function

In [36]:
anArray = np.arange(1, 7).reshape((3,2))

In [37]:
anArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
anArray.sum()

21

In [39]:
#axis 0 means sum operation on each column
axis = 0
anArray.sum(axis)

array([ 9, 12])

In [40]:
#axis 1 means sum operation on each row
axis = 1
anArray.sum(axis)

array([ 3,  7, 11])

In [41]:
anArray.mean()

3.5

In [42]:
axis = 0
anArray.mean(axis=axis)

array([ 3.,  4.])

In [43]:
axis = 1
anArray.mean(axis=axis)

array([ 1.5,  3.5,  5.5])

In [44]:
#argmax returns the index max of an array
anArray.argmax()

5

In [45]:
#argmin returns the index minimum of an array
anArray.argmin()

0

In [46]:
axis = 0
anArray.max(axis)

array([5, 6])

In [47]:
axis = 1
anArray.max(axis)

array([2, 4, 6])

In [48]:
axis = 0
anArray.min(axis)

array([1, 2])

In [49]:
axis = 1
anArray.max(axis)

array([2, 4, 6])

In [50]:
#std stands for standard deviation
anArray.std()

1.707825127659933

In [51]:
axis = 0
anArray.std(axis)

array([ 1.63299316,  1.63299316])

In [52]:
axis = 1
anArray.std(axis)

array([ 0.5,  0.5,  0.5])