# Tugas Presentasi 1

## Anggota

1.Farhan Setya Dhitama <br>
2.Ludgerus Darell Perwara <br>
3.Titus Christian <br>
4.Mahendra Okza Pradhana <br>

### Numpy

Pemrograman Python dan OpenCV

## Isi Materi

NUMPY <br>

1.Create Array <br>
2.Indexing, Slicing and Iterating <br>
3.Shape Manipulation <br>
4.

## ----------------

## List ?

1.Powerful <br>
2.Collection Of Value <br>
3.Hold different types <br>
4.Change ,add , remove <br>

In [1]:
height=[1.45,1.68,1.22,1.91,1.81]
height

[1.45, 1.68, 1.22, 1.91, 1.81]

In [2]:
weight=[65,60,45,55,30]
weight

[65, 60, 45, 55, 30]

In [3]:
BMI = height*weight**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [4]:
import numpy as np

In [5]:
np_height=np.array(height)
np_weight=np.array(weight)


In [6]:
BMI = np_weight/np_height**2
print(BMI)

[30.91557669 21.2585034  30.23380812 15.07634111  9.15722963]


## Create Array

In [7]:
arrayA=np.array([3,4,5])   #Create Array 1 Dimension

print(type(arrayA))        #Print type numpy.ndArray

print(arrayA.shape)        # Prints "(3,)"

print(arrayA[0], arrayA[1], arrayA[2])   # Prints "3 4 5"

arrayA[0] = 6                 # Change an element of the array

print(arrayA)                 # Prints "[6, 4, 5]"

<class 'numpy.ndarray'>
(3,)
3 4 5
[6 4 5]


In [8]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)             

b = np.ones((1,2))   # Create an array of all ones
print(b)              


d = np.eye(2)        # Create a 2x2 identity matrix
print(d)              
    
e = np.random.random((2,2)) # Create an array filled with random values
print(e)                    

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[1. 0.]
 [0. 1.]]
[[0.08186705 0.70975283]
 [0.90329528 0.61489039]]


## Combining Array

In [9]:
array1=np.array([[3,4],[5,6]])
array2=np.array([[7,8]])
np.concatenate((array1,array2),axis=0)  #Menjoin kan Array

array([[3, 4],
       [5, 6],
       [7, 8]])

In [10]:
np.concatenate((array1,array2.T),axis=1)

array([[3, 4, 7],
       [5, 6, 8]])

In [11]:
np.concatenate((array1,array2),axis=None)

array([3, 4, 5, 6, 7, 8])

## Operations

In [12]:
array1=np.array([[3,4,5],[6,7,8],[9,10,11]])
print(array1)
array1.shape

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


(3, 3)

In [13]:
array2=np.array([[1,2,3]])
print(array2)
array2.shape

[[1 2 3]]


(1, 3)

In [14]:
np.add(array1,array2)

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [15]:
np.subtract(array1,array2)

array([[2, 2, 2],
       [5, 5, 5],
       [8, 8, 8]])

In [16]:
np.multiply(array1,array2)

array([[ 3,  8, 15],
       [ 6, 14, 24],
       [ 9, 20, 33]])

In [17]:
np.divide(array1,array2)

array([[3.        , 2.        , 1.66666667],
       [6.        , 3.5       , 2.66666667],
       [9.        , 5.        , 3.66666667]])

In [18]:
a = np.array([10,100,1000]) 

print(a) 

print('Applying power function:')
print(np.power(a,2))
print('\n')  

[  10  100 1000]
Applying power function:
[    100   10000 1000000]




## Indexing & Slicing

In [37]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
a[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
a[-6:10:3]

array([ 7, 10])

![title](indexArray.png)